stty -ixon # disable scroll lock

if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
	# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
	# Initialization code that may require console input (password prompts, [y/n]
	# confirmations, etc.) must go above this block; everything else may go below.
	if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
		source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
	fi

	# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
	[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
fi

export ZSH_CUSTOM=~/.dotfiles/omz/custom
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
ZSH_THEME="robbyrussell"
ZSH_THEME="collin"
plugins=(
	git
	macos
	rust
)
source $ZSH/oh-my-zsh.sh

HISTFILE="$HOME/.zsh_history"
HISTSIZE=100000
SAVEHIST=100000

setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt HIST_BEEP                 # Beep when accessing nonexistent history.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.

function zshaddhistory() {
	# defang naughty commands; the entire history entry is in $1
	if [[ $1 =~ "commentedoutcommandshere" ]]; then
		1="# $1"
	fi
	if [[ $1 =~ "^builtin cd -- " ]]; then
		1=$(echo $1 | sed 's/builtin cd --/cd/')
	fi
	# write to usual history location
	print -sr -- ${1%%$'\n'}
	# do not save the history line. if you have a chain of zshaddhistory
	# hook functions, this may be more complicated to manage, depending
	# on what those other hooks do (man zshall | less -p zshaddhistory)
	return 1
}

# only init nvm if an env var is set
export NVM_DIR="$HOME/.nvm"
if [[ -n "$USE_NVM" ]]; then
	# init nvm
	[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
	[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
fi

# pyenv init
# command -v pyenv >/dev/null 2>&1 && eval "$(pyenv init -)"

if [[ -f ~/.config/broot/launcher/bash/br ]]; then
	source ~/.config/broot/launcher/bash/br
fi

# fix for zsh alt left / right not working while in tmux
bindkey "^[[1;3C" forward-word
bindkey "^[[1;3D" backward-word

if command -v starship >/dev/null 2>&1; then
	ZSH_THEME=""
	eval "$(starship init zsh)"
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
command -v atuin &> /dev/null && eval "$(atuin init zsh --disable-up-arrow)"

eval "$(direnv hook zsh)"

if command -v zoxide 2>&1 >/dev/null; then
	eval "$(zoxide init zsh)"
fi
