#!/usr/bin/env bash

set -euo pipefail

export DOTFILES_GOLINT_VERSION=v1.51.2
export DOTFILES_NVIM_VERSION=v0.10.0
export DOTFILES_BOTTOM_VERSION=0.9.6

cd ~/.dotfiles

~/.dotfiles/install-paths

osarch=$(echo "$(uname -s)-$(uname -m)" | tr '[:upper:]' '[:lower:]')
./install-${osarch}

