#!/usr/bin/env bash

echo "Installing rust utilities"

# increase the timeout for cargo for slow systems.
export CARGO_HTTP_TIMEOUT=600

if [[ $(hostname) = "nas" ]]; then
	echo "skip rust install on nas"
	exit 0
fi

cargo install \
	diskonaut \
	watchexec-cli
