#!/usr/bin/env bash

# this should be called after the main installs are done. It should be os/arch generic if possible.

set -e # exit on failure
set -u # fail if vars are not defined

echo "Updating sqlite"
sqlite=/usr/local/sqlite3/bin/sqlite3
sqlite_version=3.41.0

if ! [[ -x $(command -v $sqlite) && $sqlite_version == $($sqlite --version | awk '{print $1}') ]]; then
	echo "Installing sqlite3 $sqlite_version with readline support"
	cd "$(mktemp -d)"
	git clone -b version-$sqlite_version --depth 1 https://github.com/sqlite/sqlite.git
	cd sqlite
	./configure --enable-all --prefix=/usr/local/sqlite3
	make
	sudo make install
	cd
fi

# fzf
echo "installing fzf"
if [ ! -d ~/.fzf ]; then
	git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
	~/.fzf/install --all
else
	(cd ~/.fzf && git pull)
	~/.fzf/install --all
fi

# oh my zsh
echo "installing oh-my-zsh"
if [ ! -e ~/.oh-my-zsh ]; then
	KEEP_ZSHRC=yes \
	CHSH=no \
	RUNZSH=no \
	sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# tmux plugin manager
echo "installing tpm"
if [ ! -d ~/.tmux/plugins/tpm ]; then
	mkdir -p ~/.tmux/plugins
	git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi
(cd ~/.tmux/plugins/tpm && git pull)

# install any go programs we have defined in our dotfiles
~/.dotfiles/install-go

# install python stuff
~/.dotfiles/install-python

# install any rust programs
~/.dotfiles/install-rust

# install nodejs and npm things
~/.dotfiles/install-js
