#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=bin/load-versions
source "$(dirname "$0")/bin/load-versions"

cd ~/.dotfiles

~/.dotfiles/install-paths

case "$(uname -s)" in
    Linux) ./install-linux ;;
    Darwin) ./install-darwin ;;
esac

