#!/usr/bin/env bash

echo "Setting up python"

cd ~/.dotfiles
bin/symlink $(which python3) /usr/local/bin/python
bin/symlink $(which pip3) /usr/local/bin/pip

pip install pyright
pip install visidata
pip install urlwatch
pip install neovim-remote
