#!/usr/bin/env bash
set -euo pipefail

export HOMEBREW_NO_ENV_HINTS=1

# enable homebrew in path in case we just installed it.
export PATH=/opt/homebrew/bin:$PATH

# install homebrew
if [ ! "$(command -v brew)" ]; then
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

brew tap spring-io/tap              # required for springboot
brew tap launchdarkly/homebrew-tap  # for the LD cli
brew tap steveyegge/beads

# update homebrew packages
brew update --quiet

# ensure that xcode is installed. We'll do this using the `mas` cli.
if ! command -v mas &>/dev/null ; then
	echo "Installing mas"
	brew install --quiet --formula mas
fi

#if [[ "$(xcode-select -p)" != "/Applications/Xcode.app/Contents/Developer" ]]; then
	#echo "Installing xcode"
	#xcode_id=$(mas search xcode | rg '^\s*\d+\s+Xcode\s+\([\d\.]+\)' | awk '{print $1}')
	#mas install "$xcode_id"
	#echo "Accepting license agreement"
	#sudo xcodebuild -license accept
#fi

# openssh does not play well with macos
# microsoft-remote-desktop is deprecated
# dog is no longer maintained
# logi-options-plus is terrible when updating via homebrew
# dotnet-sdk no longer used
for pkg in openssh microsoft-remote-desktop dog logi-options-plus logi-options+ dotnet-sdk moreutils istat-menus; do
	if brew list -1 "$pkg" &>/dev/null; then
		echo "Removing $pkg"
		brew remove -f $pkg
	fi
done

brew upgrade --quiet
brew install --quiet --formula \
	act \
	aichat \
	asdf \
	bash-language-server \
	bat \
	bat-extras \
	borkdude/brew/babashka \
	broot \
	btop \
	bzip2 \
	caddy \
	chruby \
	clojure \
	clojure-lsp \
	cmake \
	colima \
	coreutils \
	daemontools \
	delta \
	detect-secrets \
	devcontainer \
	direnv \
	dust \
	exiftool \
	eza \
	fd \
	fileicon \
	fx \
	gemini-cli \
	gh \
	git-extras \
	git-machete \
	glow \
	gnuplot \
	golang \
	gomplate \
	gource \
	grpcurl \
	gum \
	helix \
	helm \
	hexyl \
	htop \
	httpie \
	hwatch \
	jj \
	jo \
	jq \
	k9s \
	kompose \
	lazydocker \
	lazygit \
	ldcli \
	less \
	libomp \
	llm \
	lnav \
	lsd \
	lua \
	lua-language-server \
	luajit-openresty \
	luarocks \
	lxc \
	minikube \
	mingw-w64 \
	mise \
	mtr \
	mutagen-io/mutagen/mutagen \
	neovim \
	nmap \
	noahgorstein/tap/jqp \
	nvr \
	ollama \
	opam \
	opencv \
	openssl \
	ov \
	pam-reattach \
	pandoc \
	parallel \
	pipx \
	protobuf \
	pstree \
	pyenv \
	ripgrep \
	ruby-install \
	ruff \
	sccache \
	semgrep \
	shellcheck \
	snitch \
	speedtest-cli \
	spotifyd \
	spotify_player \
	spring-io/tap/spring-boot \
	steveyegge/beads/bd \
	temporal \
	tig \
	tilt \
	tokei \
	tmux \
	tree \
	typescript-language-server \
	uv \
	viddy \
	watch \
	web-ext \
	wget \
	whosthere \
	xh \
	xz \
	yazi \
	zig \
	zlib \
	zls \
	zsh-autosuggestions \
	zoxide \
	;

brew install --quiet --cask --force \
	1password \
	1password-cli \
	alacritty \
	anki \
	caffeine \
	chatbox \
	cleanshot \
	discord \
	font-fira-code-nerd-font \
	font-fantasque-sans-mono \
	font-fantasque-sans-mono-nerd-font \
	font-hack-nerd-font \
	gcloud-cli \
	hammerspoon \
	hidock \
	imhex \
	kitty \
	mitmproxy \
	obsidian \
	racket \
	raycast \
	signal \
	tableplus \
	sublime-text \
	utm \
	yaak \
	zed \
	;

[[ -z "${SKIP_FIREFOX_INSTALL:-}" ]] && brew install --quiet --cask --force \
	firefox \
	;

# only install jetbrains toolbox once.
if ! brew list | grep jetbrains-toolbox &>/dev/null; then
	brew install --quiet --cask --force jetbrains-toolbox
fi

brew autoremove --quiet
brew cleanup

