#!/usr/bin/env bash

set -euo pipefail

# Parse comma-separated node versions into array
IFS=',' read -ra node_versions <<< "$(~/.dotfiles/bin/dotfiles-version node)"

get-nvm-version() {
	if [ -d ~/.nvm ]; then
        (cd ~/.nvm && git describe --tags)
	fi
}

nvm_version="$(~/.dotfiles/bin/dotfiles-version nvm)"
if ! [ "$(get-nvm-version)" = "$nvm_version" ]; then
	curl -o- "https://raw.githubusercontent.com/nvm-sh/nvm/${nvm_version}/install.sh" | bash
else
	echo "nvm ${nvm_version} already installed"
fi

# shellcheck source=/dev/null.
source ~/.nvm/nvm.sh

for nv in "${node_versions[@]}"; do
	nvm install "$nv"
done

nvm alias default 22.17.1

npm install --global yarn

# https://rustwasm.github.io/docs/book/game-of-life/setup.html
# npm install npm@latest -g
