#!/usr/bin/env bash

set -e

echo "Installing Go programs"
go version

# install our own go utilities from the go folder

dir=$(dirname $0)
cd $dir
for dir in $dir/go/*/; do
	echo "Installing $dir"
	cd $dir
	go install .
	cd ..
done

# Install commonly used go utilities that live elsewhere
export PATH=/usr/local/go/bin:$PATH

echo "Installing gopls"
go install golang.org/x/tools/gopls@latest

echo "Installing golang-migrate"
# https://github.com/golang-migrate/migrate/blob/master/cmd/migrate/README.md
go install -tags 'sqlite' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

echo "Installing charm mods"
go install github.com/charmbracelet/mods@latest

echo "Installing codesearch"
go install github.com/boyter/cs@${DOTFILES_CODESEARCH_VERSION}

# we have to install task manually since it's not in apt
if [[ $(task --version 2>/dev/null | grep -o "$DOTFILES_TASK_VERSION") != "$DOTFILES_TASK_VERSION" ]]; then 
	echo "Installing task ${DOTFILES_TASK_VERSION}"
	go install github.com/go-task/task/v3/cmd/task@v${DOTFILES_TASK_VERSION}
fi

