#!/usr/bin/env bash

set -euo pipefail

mkdir -p ~/.config
mkdir -p ~/.ssh
mkdir -p ~/.ssh/control
mkdir -p ~/.config/bottom

chmod 700 ~/.ssh
chmod 600 ~/.dotfiles/ssh/config

ln -sf ~/.dotfiles/zsh/.zshrc ~/.zshrc
ln -sf ~/.dotfiles/zsh/.zshenv ~/.zshenv
ln -sf ~/.dotfiles/zsh/.zprofile ~/.zprofile

mkdir -p ~/.config/rustfmt/
ln -sf ~/.dotfiles/rust/rustfmt.toml ~/.config/rustfmt/

mkdir -p ~/.config/zed/
ln -sf ~/.dotfiles/zed/settings.json ~/.config/zed/
ln -sf ~/.dotfiles/zed/keymap.json ~/.config/zed/
ln -sf ~/.dotfiles/zed/tasks.json ~/.config/zed/

if [[ -d "$HOME/Library/Application Support/Firefox/Profiles/zdsf67fe.default" ]]; then
    ln -sf ~/.dotfiles/firefox/profile/user.js "$HOME/Library/Application Support/Firefox/Profiles/zdsf67fe.default/user.js"
fi

# os specific symlinking
if [[ "$(uname)" =~ "Darwin" ]]; then
    # claude
    mkdir -p ~/Library/Application\ Support/Claude
    ln -sf ~/.dotfiles/ai/claude/claude_desktop_config.json ~/Library/Application\ Support/Claude/

	# lazygit
	mkdir -p ~/Library/Application\ Support/lazygit
	bin/symlink ~/.dotfiles/lazygit/config.yml ~/Library/Application\ Support/lazygit

	# urlwatch
	bin/symlink ~/.dotfiles/urlwatch ~/Library/Application\ Support/urlwatch

	# nushell
	mkdir -p ~/Library/Application\ Support/nushell
	bin/symlink ~/.dotfiles/nushell/config.nu ~/Library/Application\ Support/nushell
	bin/symlink ~/.dotfiles/nushell/env.nu ~/Library/Application\ Support/nushell

	# bacon
	mkdir -p ~/Library/Application\ Support/org.dystroy.bacon
	bin/symlink ~/.dotfiles/bacon/prefs.toml ~/Library/Application\ Support/org.dystroy.bacon
else
	mkdir -p ~/.config/lazygit
	bin/symlink ~/.dotfiles/lazygit/config.yml ~/.config/lazygit/config.yml
	bin/symlink ~/.dotfiles/urlwatch ~/.cofnig/urlwatch
fi

if [ -d ~/.config/broot ]; then
    # we will replace it with our symlinked dir
    rm -rf ~/.config/broot
fi

if ! [[ -d /usr/local/bin ]]; then
    sudo mkdir -p /usr/local/bin
    sudo chown $USER /usr/local/bin
fi

if [[ -d ~/code/notes ]]; then
    ln -sf ~/.dotfiles/obsidian/.obsidian.vimrc ~/code/notes/.obsidian.vimrc
fi


bin/symlink ~/.dotfiles/atuin                      ~/.config/atuin
bin/symlink ~/.dotfiles/ghostty                    ~/.config/ghostty
bin/symlink ~/.dotfiles/broot                      ~/.config/broot
bin/symlink ~/.dotfiles/btm/bottom.toml            ~/.config/bottom/
bin/symlink ~/.dotfiles/direnv                     ~/.config/direnv
bin/symlink ~/.dotfiles/dlv                        ~/.config/dlv
bin/symlink ~/.dotfiles/git/.gitconfig             ~
bin/symlink ~/.dotfiles/git/.gitignore_global      ~
bin/symlink ~/.dotfiles/git/tigrc                  ~/.tigrc
bin/symlink ~/.dotfiles/hammerspoon                ~/.hammerspoon
bin/symlink ~/.dotfiles/idea/.ideavimrc            ~/.ideavimrc
bin/symlink ~/.dotfiles/kitty                      ~/.config/kitty
bin/symlink ~/.dotfiles/lsd                        ~/.config/lsd
bin/symlink ~/.dotfiles/mutagen/.mutagen.yml       ~/.mutagen.yml
bin/symlink ~/.dotfiles/nvim                       ~/.config/nvim
bin/symlink ~/.dotfiles/powerline                  ~/.config/powerline
bin/symlink ~/.dotfiles/ripgrep/.ripgrep.conf      ~/.ripgrep.conf
bin/symlink ~/.dotfiles/runcom/.imwheelrc          ~
bin/symlink ~/.dotfiles/runcom/p10k.zsh            ~/.p10k.zsh
bin/symlink ~/.dotfiles/sqlite/sqliterc            ~/.sqliterc
bin/symlink ~/.dotfiles/ssh/config                 ~/.ssh/config
bin/symlink ~/.dotfiles/starship/starship.toml     ~/.config/
bin/symlink ~/.dotfiles/tailspin                   ~/.config/tailspin
bin/symlink ~/.dotfiles/taskfile/taskfile.yml      ~/.taskfile
bin/symlink ~/.dotfiles/tmux-powerline             ~/.config/tmux-powerline
bin/symlink ~/.dotfiles/tmux/tmux.conf             ~/.tmux.conf
bin/symlink ~/.dotfiles/tmux/tmux.conf             ~/.tmux.conf
bin/symlink ~/.dotfiles/tmuxinator                 ~/.config/tmuxinator
bin/symlink ~/.dotfiles/tmuxinator/.tmuxinator.yml ~
bin/symlink ~/.dotfiles/zellij                     ~/.config/zellij
bin/symlink ~/.dotfiles/cargo/config.toml          ~/.cargo/config.toml
bin/symlink ~/.dotfiles/bin/tm                     /usr/local/bin

touch ~/.tmux.custom.conf

