#!/usr/bin/env bash

set -euo pipefail

echo "Installing asdf"
go install github.com/asdf-vm/asdf/cmd/asdf@v0.16.0

export PATH=~/go/bin:$PATH

asdf plugin add lua-language-server

asdf install lua-language-server latest || true
