#!/usr/bin/env bash

set -euo pipefail

echo "Installing Go programs"
go version

# install our own go utilities from the go folder

dir=$(dirname $0)
cd $dir
for dir in $dir/go/*/; do
	echo "Installing $dir"
	cd $dir
	go install .
	cd ..
done

# Install commonly used go utilities that live elsewhere
export PATH=/usr/local/go/bin:$PATH

echo "Installing gopls"
go install golang.org/x/tools/gopls@latest

echo "Installing golang-migrate"
# https://github.com/golang-migrate/migrate/blob/master/cmd/migrate/README.md
go install -tags 'sqlite' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

echo "Installing charm mods"
# go install github.com/charmbracelet/mods@latest

echo "Installing codesearch"
go install "github.com/boyter/cs@$(~/.dotfiles/bin/dotfiles-version codesearch)"

echo "Installing gpterm"
go install github.com/collinvandyck/gpterm/cmd/gpterm@latest

# we have to install task manually since it's not in apt
task_version="$(~/.dotfiles/bin/dotfiles-version task)"
if [[ $(task --version 2>/dev/null | grep -o "$task_version") != "$task_version" ]]; then
	echo "Installing task ${task_version}"
	go install "github.com/go-task/task/v3/cmd/task@v${task_version}"
fi

echo "Installing air"
go install github.com/air-verse/air@latest
