#!/usr/bin/env bash

set -euo pipefail

export HOMEBREW_NO_ENV_HINTS=1

# enable homebrew in path in case we just installed it.
export PATH=/opt/homebrew/bin:$PATH

# install homebrew
if [ ! "$(command -v brew)" ]; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# update homebrew packages
brew update --quiet

# ensure that xcode is installed. We'll do this using the `mas` cli.
if ! command -v mas &>/dev/null ; then
    echo "Installing mas"
    brew install --quiet --formula mas
fi
if [[ "$(xcode-select -p)" != "/Applications/Xcode.app/Contents/Developer" ]]; then
    echo "Installing xcode"
    xcode_id=$(mas search xcode | rg '^\s*\d+\s+Xcode\s+\([\d\.]+\)' | awk '{print $1}')
    mas install "$xcode_id"
    echo "Accepting license agreement"
    sudo xcodebuild -license accept
fi

# openssh does not play well with macos
# microsoft-remote-desktop is deprecated
# dog is no longer maintained
# logi-options-plus is terrible when updating via homebrew
# dotnet-sdk no longer used
for pkg in openssh microsoft-remote-desktop dog logi-options-plus logi-options+ dotnet-sdk; do
    if brew list -1 | grep -q "^${pkg}\$"; then
        echo "Removing $pkg"
        brew remove -f $pkg
    fi
done

brew upgrade --quiet
brew install --quiet --formula \
    aichat \
    asdf \
    bash-language-server \
    bat-extras \
    broot \
    btop \
    bzip2 \
    caddy \
    chruby \
    clojure \
    clojure-lsp \
    cmake \
    colima \
    coreutils \
    devcontainer \
    direnv \
    dust \
    eza \
    fd \
    fileicon \
    fx \
    gh \
    git-extras \
    git-machete \
    glow \
    gnuplot \
    golang \
    gource \
    gradle \
    grpcurl \
    gum \
    helm \
    hexyl \
    htop \
    httpie \
    hwatch \
    kompose \
    lazydocker \
    lazygit \
    less \
    libomp \
    llm \
    lnav \
    lsd \
    lua \
    lua-language-server \
    luajit-openresty \
    luarocks \
    lxc \
    minikube \
    mingw-w64 \
    mtr \
    mutagen-io/mutagen/mutagen \
    neovim \
    nmap \
    nvr \
    ollama \
    opam \
    pam-reattach \
    pandoc \
    pipx \
    protobuf \
    pstree \
    pyenv \
    ripgrep \
    ruby-install \
    ruff \
    sccache \
    semgrep \
    shellcheck \
    temporal \
    tig \
    tilt \
    tokei \
    tmux \
    tree \
    typescript-language-server \
    uv \
    viddy \
    watch \
    web-ext \
    wget \
    xz \
    zig \
    zlib \
    zsh-autosuggestions \
    zoxide \
    ;

brew install --quiet --cask --force \
    1password \
    1password-cli \
    anki \
    caffeine \
    chatbox \
    cleanshot \
    discord \
    firefox \
    font-fira-code-nerd-font \
    font-fantasque-sans-mono \
    font-fantasque-sans-mono-nerd-font \
    font-hack-nerd-font \
    google-cloud-sdk \
    imhex \
    istat-menus \
    jetbrains-toolbox \
    kitty \
    mitmproxy \
    ngrok \
    obs \
    obsidian \
    racket \
    raycast \
    signal \
    tableplus \
    sublime-text \
    utm \
    yaak \
    yubico-yubikey-manager \
    zed \
    ;

brew install --quiet --cask --no-quarantine \
    alacritty \
    ;

brew autoremove --quiet

