#!/usr/bin/env bash

# Common linux setup for all architectures.

set -eu

# shellcheck source=bin/load-versions
source "$(dirname "$0")/bin/load-versions"

sudo apt update
sudo apt install -y \
	apt-transport-https \
	asciinema \
	autoconf \
	automake \
	bat \
	btop \
	build-essential \
	ca-certificates \
	cmake \
	curl \
	direnv \
	doxygen \
	fatrace \
	fd-find \
	fswatch \
	g++ \
	gettext \
	gh \
	gnome-tweaks \
	gnupg \
	htop \
	httpie \
	hyperfine \
	iproute2 \
	iputils-ping \
	jq \
	just \
	kitty-terminfo \
	lazygit \
	libfuse2 \
	libluajit-5.1-dev \
	libpcap-dev \
	librust-alsa-sys-dev \
	libssl-dev \
	libtool \
	libtool-bin \
	libtree-sitter-dev \
	lld \
	lsb-release \
	lsd \
	man \
	man-db \
	net-tools \
	nethogs \
	ninja-build \
	nmap \
	nodejs \
	openssh-server \
	pipx \
	pkg-config \
	protobuf-compiler \
	psmisc \
	python-is-python3 \
	python3-pip \
	ripgrep \
	shellcheck \
	shfmt \
	snapd \
	software-properties-common \
	sqlite3 \
	starship \
	tailspin \
	tcl \
	tig \
	tmux \
	tokei \
	traceroute \
	tree \
	unzip \
	valgrind \
	wget \
	xh \
	xsel \
	zoxide \
	zsh \
	;

if [[ "$(uname -a)" =~ WSL2 ]]; then
	sudo apt install -y linux-tools-generic
fi

sudo apt autoremove -y
sudo chsh -s "$(which zsh)" "$USER"

# for testing binaries on a fresh install
export PATH="/snap/bin:/usr/local/bin:/usr/local/go/bin:$PATH"

# golang
(
	echo "checking golang"
	if ! [[ "$(go version 2>/dev/null || true)" == *"go version ${DOTFILES_GO_VERSION}"* ]]; then
		cd "$(mktemp -d)"
		case "$(uname -m)" in
			aarch64) arch=arm64;;
			*) arch="$(uname -m)";;
		esac
		artifact="go${DOTFILES_GO_VERSION}.linux-${arch}.tar.gz"
		curl -LO "https://go.dev/dl/${artifact}"
		sudo rm -rf /usr/local/go
		sudo tar -C /usr/local -xzf "$artifact"
	fi
)

# neovim
(
	echo "checking neovim"
	if ! [[ "$(nvim --version 2>/dev/null || true)" == *"NVIM ${DOTFILES_NVIM_VERSION}"* ]]; then
		cd "$(mktemp -d)"
		git clone --depth 1 --branch "${DOTFILES_NVIM_VERSION}" https://github.com/neovim/neovim.git
		cd neovim
		make CMAKE_BUILD_TYPE=RelWithDebInfo
		sudo make install
		sudo cp ~/.dotfiles/bin/exec-nvim /usr/local/bin/vim
		sudo cp ~/.dotfiles/bin/exec-nvim /usr/local/bin/vi
		echo "done installing neovim"
	else
		echo "nvim check ok"
	fi
)

# add tailscale
[[ -n "${INSTALL_TAILSCALE:-}" ]] && (
	echo "checking tailscale"
	# Exit node stuff
	ts_conf=/etc/sysctl.d/99-tailscale.conf
	if ! [ -f $ts_conf ]; then
		echo 'net.ipv4.ip_forward = 1' | sudo tee -a $ts_conf
		echo 'net.ipv6.conf.all.forwarding = 1' | sudo tee -a $ts_conf
		sudo sysctl -p $ts_conf
	fi

	# Add Tailscale's GPG key
	sudo mkdir -p --mode=0755 /usr/share/keyrings
	curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/noble.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
	# Add the tailscale repository
	curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/noble.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list
	# Install Tailscale
	sudo apt-get update && sudo apt-get install -y tailscale tailscale-nginx-auth
	# Start Tailscale!
	# sudo tailscale up --advertise-exit-node || true
	sudo tailscale up || true
	# enable tailscale nginx auth
	sudo systemctl enable --now tailscale.nginx-auth.socket
)

# bash-language-server
(
	echo "checking bash-language-server"
	if ! [[ "$(bash-language-server --version 2>/dev/null || true)" == *"4.7.0"* ]]; then
		sudo snap install bash-language-server --classic
	fi
)

# delta pager
(
	if ! [[ "$(delta --version)" = "delta ${DOTFILES_DELTA_VERSION}" ]]; then
		echo "installing delta pager ${DOTFILES_DELTA_VERSION}"
		cd "$(mktemp -d)"

		case "$(uname -m)" in
			aarch64) arch=arm64;;
			*) arch="$(uname -m)";;
		esac
		filename="git-delta_${DOTFILES_DELTA_VERSION}_${arch}.deb"
		url="https://github.com/dandavison/delta/releases/download/${DOTFILES_DELTA_VERSION}/${filename}"
		echo "Downloading from $url"
		wget "$url"
		sudo dpkg -i $filename
	fi
)

# run generic os-agnostic installs
~/.dotfiles/install-common
