#!/usr/bin/env bash
set -euo pipefail

usage() {
    echo "usage: $(basename "$0") [--no-npm-install]"
    exit 1
}


echo "Installing Claude requirements..."

mkdir -p ~/.claude/servers/
mkdir -p ~/.claude/storage/memory

if ! [[ -f ~/.claude/servers/.env ]]; then
echo "Creating .env file"
cat > ~/.claude/servers/.env <<EOF
EXA_API_KEY=
NYTIMES_API_KEY=
EOF
fi

if ! [[ -f ~/.claude/storage/memory/memory.json ]]; then
    echo "Creating memory.json file"
    cat > ~/.claude/storage/memory/memory.json <<EOF
{}
EOF
fi

if ! command -v tsx &>/dev/null; then
    echo "Installing tsx"
    npm install --global tsx
fi

ensure_mcp() {
    local repo dir
    repo=$1
    dir=~/.claude/servers/$(basename "$repo" .git)
    echo "Configuring $repo"
    if ! [[ -d $dir ]]; then
        echo "Cloning $repo"
        git clone "$repo" "$dir"
        (cd "$dir" && npm install --no-package-lock)
    else
        (cd "$dir" && {
            local before=""
            before=$(git rev-parse HEAD)
            git pull >/dev/null
            if [[ $before != $(git rev-parse HEAD) ]]; then
                npm install --no-package-lock
            fi
        })
    fi
}

ensure_mcp git@github.com:collinvandyck/mcp-servers.git
ensure_mcp git@github.com:exa-labs/exa-mcp-server.git
ensure_mcp git@github.com:angheljf/nyt.git

# install claude code
npm install -g @anthropic-ai/claude-code

