#!/usr/bin/env bash

set -euo pipefail

mkdir -p ~/.config
mkdir -p ~/.ssh
mkdir -p ~/.ssh/control
mkdir -p ~/.config/bottom

chmod 700 ~/.ssh
chmod 600 ~/.dotfiles/ssh/config

ln -sf ~/.dotfiles/zsh/.zshrc ~/.zshrc
ln -sf ~/.dotfiles/zsh/.zshenv ~/.zshenv
ln -sf ~/.dotfiles/zsh/.zprofile ~/.zprofile

mkdir -p ~/.config/rustfmt/
ln -sf ~/.dotfiles/rust/rustfmt.toml ~/.config/rustfmt/

mkdir -p ~/.config/zed/
ln -sf ~/.dotfiles/zed/settings.json ~/.config/zed/
ln -sf ~/.dotfiles/zed/keymap.json ~/.config/zed/
ln -sf ~/.dotfiles/zed/tasks.json ~/.config/zed/

rm -rf ~/.config/yazi
ln -sf ~/.dotfiles/yazi/ ~/.config

symlink() { ~/.dotfiles/bin/symlink "$@"; }

for dir in "$HOME/Library/Application Support/Firefox/Profiles"/*; do
	if [[ -d "$dir" ]]; then
		ln -sf ~/.dotfiles/firefox/profile/chrome "$dir"/
		ln -sf ~/.dotfiles/firefox/profile/user.js "$dir"/
	fi
done

# os specific symlinking
if [[ "$(uname)" =~ "Darwin" ]]; then
    # claude
    mkdir -p ~/Library/Application\ Support/Claude
    ln -sf ~/.dotfiles/ai/claude/claude_desktop_config.json ~/Library/Application\ Support/Claude/
	mkdir -p ~/.claude
	ln -sf ~/.dotfiles/ai/claude/code/CLAUDE.md ~/.claude/
	ln -sf ~/.dotfiles/ai/claude/code/settings.json ~/.claude/
	ln -sf ~/.dotfiles/ai/claude/code/commands ~/.claude/

	# lazygit
	mkdir -p ~/Library/Application\ Support/lazygit
	symlink ~/.dotfiles/lazygit/config.yml ~/Library/Application\ Support/lazygit

	# urlwatch
	symlink ~/.dotfiles/urlwatch ~/Library/Application\ Support/urlwatch

	# nushell
	mkdir -p ~/Library/Application\ Support/nushell
	symlink ~/.dotfiles/nushell/config.nu ~/Library/Application\ Support/nushell
	symlink ~/.dotfiles/nushell/env.nu ~/Library/Application\ Support/nushell

	# bacon
	mkdir -p ~/Library/Application\ Support/org.dystroy.bacon
	symlink ~/.dotfiles/bacon/prefs.toml ~/Library/Application\ Support/org.dystroy.bacon
else
	mkdir -p ~/.config/lazygit
	symlink ~/.dotfiles/lazygit/config.yml ~/.config/lazygit/config.yml
	symlink ~/.dotfiles/urlwatch ~/.cofnig/urlwatch
fi

if [ -d ~/.config/broot ]; then
    # we will replace it with our symlinked dir
    rm -rf ~/.config/broot
fi

if ! [[ -d /usr/local/bin ]]; then
    sudo mkdir -p /usr/local/bin
    sudo chown "$USER" /usr/local/bin
fi

# we do not symlink obsidian into the notes repo anymore b/c it doesn't work
# when using obsidian on windows
ovimrc=~/code/notes/.obsidian.vimrc
[[ -L $ovimrc ]] && rm $ovimrc
[[ -d ~/code/notes ]] && cp ~/.dotfiles/obsidian/.obsidian.vimrc ~/code/notes


symlink ~/.dotfiles/atuin                      ~/.config/atuin
symlink ~/.dotfiles/ghostty                    ~/.config/ghostty
symlink ~/.dotfiles/broot                      ~/.config/broot
symlink ~/.dotfiles/btm/bottom.toml            ~/.config/bottom/
symlink ~/.dotfiles/direnv                     ~/.config/direnv
symlink ~/.dotfiles/dlv                        ~/.config/dlv
symlink ~/.dotfiles/git/.gitconfig             ~
symlink ~/.dotfiles/git/.gitignore_global      ~
symlink ~/.dotfiles/git/tigrc                  ~/.tigrc
symlink ~/.dotfiles/hammerspoon                ~/.hammerspoon
symlink ~/.dotfiles/idea/.ideavimrc            ~/.ideavimrc
symlink ~/.dotfiles/kitty                      ~/.config/kitty
symlink ~/.dotfiles/lsd                        ~/.config/lsd
symlink ~/.dotfiles/mutagen/.mutagen.yml       ~/.mutagen.yml
symlink ~/.dotfiles/nvim                       ~/.config/nvim
symlink ~/.dotfiles/powerline                  ~/.config/powerline
symlink ~/.dotfiles/ripgrep/.ripgrep.conf      ~/.ripgrep.conf
symlink ~/.dotfiles/runcom/.imwheelrc          ~
symlink ~/.dotfiles/runcom/p10k.zsh            ~/.p10k.zsh
symlink ~/.dotfiles/sqlite/sqliterc            ~/.sqliterc
symlink ~/.dotfiles/ssh/config                 ~/.ssh/config
symlink ~/.dotfiles/starship/starship.toml     ~/.config/
symlink ~/.dotfiles/tailspin                   ~/.config/tailspin
symlink ~/.dotfiles/taskfile/taskfile.yml      ~/.taskfile
symlink ~/.dotfiles/tmux-powerline             ~/.config/tmux-powerline
symlink ~/.dotfiles/tmux/tmux.conf             ~/.tmux.conf
symlink ~/.dotfiles/tmux/tmux.conf             ~/.tmux.conf
symlink ~/.dotfiles/tmuxinator                 ~/.config/tmuxinator
symlink ~/.dotfiles/tmuxinator/.tmuxinator.yml ~
symlink ~/.dotfiles/zellij                     ~/.config/zellij
symlink ~/.dotfiles/cargo/config.toml          ~/.cargo/config.toml

# old tm path
rm -f /usr/local/bin/tm
touch ~/.tmux.custom.conf

