#!/usr/bin/env bash

echo "Installing rust utilities"

# increase the timeout for cargo for slow systems.
export CARGO_HTTP_TIMEOUT=600

if [[ "${DOTFILES_SKIP_RUST_UTILS}" = "true" ]]; then
	echo "Skipping rust utils"
	exit 0
fi

cargo install \
	diskonaut \
	watchexec-cli
