#!/usr/bin/env bash

echo "Installing cargo binstall"
curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

echo "Installing rust utilities"

cargo binstall -y \
	bacon \
	cargo-nextest \
	cargo-watch \
	diskonaut \
	erdtree \
	mdbook \
	starship \
	trunk \
	watchexec-cli \
	;
