[package]
name = "cargo-tweak"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.29", features = ["derive"] }
tempfile = "3.16.0"
toml_edit = "0.22.24"

[lints]
rust = {}

