" Generated by vim-plug
" Tue Apr 25 12:37:10 2023
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['LuaSnip'].commit = '500981ff6cefc7343e3959ef0f939bd0bfd49ba9'
silent! let g:plugs['bat.vim'].commit = 'cc038af97410bfc8da2e29f7eefa51f565346993'
silent! let g:plugs['cmp-buffer'].commit = '3022dbc9166796b644a841a02de8dd1cc1d311fa'
silent! let g:plugs['cmp-cmdline'].commit = '5af1bb7d722ef8a96658f01d6eb219c4cf746b32'
silent! let g:plugs['cmp-nvim-lsp'].commit = '0e6b2ed705ddcff9738ec4ea838141654f12eeef'
silent! let g:plugs['cmp-path'].commit = '91ff86cd9c29299a64f968ebb45846c485725f23'
silent! let g:plugs['cmp_luasnip'].commit = '18095520391186d634a0045dacaa346291096566'
silent! let g:plugs['copilot.vim'].commit = 'b6e5624351ba735e25eb8864d7d22819aad00606'
silent! let g:plugs['fzf'].commit = '65dd2bb42947d4ede31d160214f3a4c6fdc619e1'
silent! let g:plugs['fzf.vim'].commit = 'dc71692255b62d1f67dc55c8e51ab1aa467b1d46'
silent! let g:plugs['gruvbox'].commit = 'bf2885a95efdad7bd5e4794dd0213917770d79b7'
silent! let g:plugs['lualine.nvim'].commit = '84ffb80e452d95e2c46fa29a98ea11a240f7843e'
silent! let g:plugs['nvim-autopairs'].commit = '7566a86f44bb72ba2b1a609f528a27d93241502d'
silent! let g:plugs['nvim-cmp'].commit = 'e28fb7a730b1bd425fdddfdbd3d36bb84bd77611'
silent! let g:plugs['nvim-lspconfig'].commit = '710c45bd13928c1f37ef0a714fd49b75f00d7d5e'
silent! let g:plugs['nvim-osc52'].commit = '47ce7ee2396fa3ee4fb6b0e0ef14ba06f9c9bd31'
silent! let g:plugs['nvim-tree.lua'].commit = 'bb375fb20327c49920c41d2b51c1ce2f4fe7deb3'
silent! let g:plugs['nvim-treesitter'].commit = '87faf372eb517077cc600c4e653e4fb3252d02ac'
silent! let g:plugs['nvim-web-devicons'].commit = '4ec26d67d419c12a4abaea02f1b6c57b40c08d7e'
silent! let g:plugs['plenary.nvim'].commit = '9ac3e9541bbabd9d73663d757e4fe48a675bb054'
silent! let g:plugs['project.nvim'].commit = '8c6bad7d22eef1b71144b401c9f74ed01526a4fb'
silent! let g:plugs['telescope.nvim'].commit = '9de317bdea2bc393074651179c4fc7f93e9b2d56'
silent! let g:plugs['toggleterm.nvim'].commit = '68fdf851c2b7901a7065ff129b77d3483419ddce'
silent! let g:plugs['trouble.nvim'].commit = 'd56bfc0c501ced4002a57cb60433362fb2ce9c4d'
silent! let g:plugs['vim-autoread'].commit = '7e83d47a71fdafc271005fc39c89863204278c77'
silent! let g:plugs['vim-fugitive'].commit = 'e6651a79facf5cc2b7c554fdc19eb8a9fe89602c'
silent! let g:plugs['vim-misc'].commit = '3e6b8fb6f03f13434543ce1f5d24f6a5d3f34f0b'
silent! let g:plugs['vim-nix'].commit = '7d23e97d13c40fcc6d603b291fe9b6e5f92516ee'
silent! let g:plugs['vim-rhubarb'].commit = 'ee69335de176d9325267b0fd2597a22901d927b1'
silent! let g:plugs['vim-session'].commit = '9e9a6088f0554f6940c19889d0b2a8f39d13f2bb'

PlugUpdate!

