" Generated by vim-plug
" Sat Apr 15 12:26:05 2023
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['LuaSnip'].commit = '500981ff6cefc7343e3959ef0f939bd0bfd49ba9'
silent! let g:plugs['autoclose.nvim'].commit = 'c4db42ffc0edbd244502be951c142df0c8a7e582'
silent! let g:plugs['bat.vim'].commit = 'cc038af97410bfc8da2e29f7eefa51f565346993'
silent! let g:plugs['cmp-buffer'].commit = '3022dbc9166796b644a841a02de8dd1cc1d311fa'
silent! let g:plugs['cmp-cmdline'].commit = 'af88e700417c6449719fc77f6f3745f88e42d5da'
silent! let g:plugs['cmp-nvim-lsp'].commit = '0e6b2ed705ddcff9738ec4ea838141654f12eeef'
silent! let g:plugs['cmp-path'].commit = '91ff86cd9c29299a64f968ebb45846c485725f23'
silent! let g:plugs['copilot.vim'].commit = 'b6e5624351ba735e25eb8864d7d22819aad00606'
silent! let g:plugs['friendly-snippets'].commit = '8f26df063f0fdabc27845c7aed56db9102d385e8'
silent! let g:plugs['fzf'].commit = '96670d5f16dcf23d590eb1d83d1de351b2e8fb15'
silent! let g:plugs['fzf.vim'].commit = 'dc71692255b62d1f67dc55c8e51ab1aa467b1d46'
silent! let g:plugs['gruvbox'].commit = 'bf2885a95efdad7bd5e4794dd0213917770d79b7'
silent! let g:plugs['nvim-cmp'].commit = '777450fd0ae289463a14481673e26246b5e38bf2'
silent! let g:plugs['nvim-lspconfig'].commit = 'e52efca5d4f5536533d447ec0d97e4d525b37ace'
silent! let g:plugs['nvim-tree.lua'].commit = '6ad5c26f4d44791699c5538d9773cb141ba033e7'
silent! let g:plugs['nvim-treesitter'].commit = 'dad0864fa324d1df88242a978e9d7de383c5be68'
silent! let g:plugs['nvim-web-devicons'].commit = '4ec26d67d419c12a4abaea02f1b6c57b40c08d7e'
silent! let g:plugs['plenary.nvim'].commit = '9ac3e9541bbabd9d73663d757e4fe48a675bb054'
silent! let g:plugs['project.nvim'].commit = '8c6bad7d22eef1b71144b401c9f74ed01526a4fb'
silent! let g:plugs['telescope.nvim'].commit = '9de317bdea2bc393074651179c4fc7f93e9b2d56'
silent! let g:plugs['toggleterm.nvim'].commit = '1c5996ee3c30b54751093fe68d40676859e7778f'
silent! let g:plugs['trouble.nvim'].commit = '2ae7237c2917d661f458443c9a88680f8ca2d7b2'
silent! let g:plugs['vim-autoread'].commit = '7e83d47a71fdafc271005fc39c89863204278c77'
silent! let g:plugs['vim-fugitive'].commit = 'e6651a79facf5cc2b7c554fdc19eb8a9fe89602c'
silent! let g:plugs['vim-misc'].commit = '3e6b8fb6f03f13434543ce1f5d24f6a5d3f34f0b'
silent! let g:plugs['vim-nix'].commit = '7d23e97d13c40fcc6d603b291fe9b6e5f92516ee'
silent! let g:plugs['vim-rhubarb'].commit = 'ee69335de176d9325267b0fd2597a22901d927b1'
silent! let g:plugs['vim-session'].commit = '9e9a6088f0554f6940c19889d0b2a8f39d13f2bb'

PlugUpdate!


