" Generated by vim-plug
" Sat Oct 14 11:29:11 2023
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['LuaSnip'].commit = '500981ff6cefc7343e3959ef0f939bd0bfd49ba9'
silent! let g:plugs['bat.vim'].commit = 'cc038af97410bfc8da2e29f7eefa51f565346993'
silent! let g:plugs['cmp-buffer'].commit = '3022dbc9166796b644a841a02de8dd1cc1d311fa'
silent! let g:plugs['cmp-cmdline'].commit = '8ee981b4a91f536f52add291594e89fb6645e451'
silent! let g:plugs['cmp-nvim-lsp'].commit = '44b16d11215dce86f253ce0c30949813c0a90765'
silent! let g:plugs['cmp-path'].commit = '91ff86cd9c29299a64f968ebb45846c485725f23'
silent! let g:plugs['cmp_luasnip'].commit = '05a9ab28b53f71d1aece421ef32fee2cb857a843'
silent! let g:plugs['copilot.vim'].commit = '998cf5ab1b85e844c7e8edb864a997e590df7182'
silent! let g:plugs['fzf'].commit = '3e1735b06eb458525b496645dd6cc9ffc606f61d'
silent! let g:plugs['fzf.vim'].commit = 'd1016dbd7cec2d2a3bb5863776c84b4034e4b85e'
silent! let g:plugs['github-nvim-theme'].commit = '48f95f763e1a98e508260a20e448c3ff2d91213a'
silent! let g:plugs['gruvbox'].commit = 'f1ecde848f0cdba877acb0c740320568252cc482'
silent! let g:plugs['indent-blankline.nvim'].commit = '0fe34b4c1b926e106d105d3ae88ef6cbf6743572'
silent! let g:plugs['lualine.nvim'].commit = '45e27ca739c7be6c49e5496d14fcf45a303c3a63'
silent! let g:plugs['moonfly'].commit = 'ae907fd6271a6d28e6c46b2b491d3bce28446e74'
silent! let g:plugs['nvim-autopairs'].commit = '748e72c05495a3d30e88a6ef04b21697019a9aa9'
silent! let g:plugs['nvim-cmp'].commit = '5dce1b778b85c717f6614e3f4da45e9f19f54435'
silent! let g:plugs['nvim-lspconfig'].commit = '8f3ddc448769f563248654a5099c943c7139137e'
silent! let g:plugs['nvim-osc52'].commit = '78652ac4c992214e46fccb95364044d98b0a6a44'
silent! let g:plugs['nvim-tree.lua'].commit = '4054fc4be31bbb34da3a96be1cc03e09aa13bbbb'
silent! let g:plugs['nvim-treesitter'].commit = 'ad02fbcdfc391017cad462e04e4740d2887cfa2e'
silent! let g:plugs['nvim-web-devicons'].commit = '3af745113ea537f58c4b1573b64a429fefad9e07'
silent! let g:plugs['plenary.nvim'].commit = '50012918b2fc8357b87cff2a7f7f0446e47da174'
silent! let g:plugs['project.nvim'].commit = '8c6bad7d22eef1b71144b401c9f74ed01526a4fb'
silent! let g:plugs['telescope.nvim'].commit = '7011eaae0ac1afe036e30c95cf80200b8dc3f21a'
silent! let g:plugs['toggleterm.nvim'].commit = 'c80844fd52ba76f48fabf83e2b9f9b93273f418d'
silent! let g:plugs['trouble.nvim'].commit = '02219b557d4726a789be58c5d6bd6e139c46a9fe'
silent! let g:plugs['vim-autoread'].commit = '24061f84652d768bfb85d222c88580b3af138dab'
silent! let g:plugs['vim-fugitive'].commit = 'cbe9dfa162c178946afa689dd3f42d4ea8bf89c1'
silent! let g:plugs['vim-misc'].commit = '3e6b8fb6f03f13434543ce1f5d24f6a5d3f34f0b'
silent! let g:plugs['vim-nix'].commit = '1e8d3cc4d74f40fb384cd1739739543fe117ff61'
silent! let g:plugs['vim-rhubarb'].commit = 'ee69335de176d9325267b0fd2597a22901d927b1'
silent! let g:plugs['vim-session'].commit = '9e9a6088f0554f6940c19889d0b2a8f39d13f2bb'

PlugUpdate!

