--color=auto
--smart-case
--line-buffered
--colors=line:bg:black
--colors=line:fg:blue
--colors=match:bg:black
--colors=match:fg:red
--colors=path:bg:black
--colors=path:fg:green
--multiline-dotall
--glob-case-insensitive
--type-add=noise:*_test.go
--type-add=noise:*mock.go
--type-add=noise:*_mock.go
--type-add=noise:*.pb.go
